#!/usr/bin/env sh
spacebar -m config position             top
spacebar -m config height               26
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15

spacebar -m config text_font            "Hack Nerd Font Mono:Bold:12.0"
spacebar -m config icon_font            "Hack Nerd Font Mono:Regular:12.0"

spacebar -m config background_color     0xff202020
spacebar -m config foreground_color     0xffa8a8a8
spacebar -m config space_icon_color     0xff458588
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xffa8a8a8
spacebar -m config clock_icon_color     0xffa8a8a8

spacebar -m config title                on

spacebar -m config spaces               on
spacebar -m config space_icon           
# spacebar -m config space_icon_strip        
spacebar -m config space_icon_strip     daily notes web code music writ video zoom dump

spacebar -m config clock                on
spacebar -m config clock_icon           
spacebar -m config clock_format         "%m/%d/%y %R"

spacebar -m config power                on
spacebar -m config power_icon_strip      

spacebar -m config right_shell          on
spacebar -m config right_shell_command  "yabai -m query --spaces --space | jq -r '.type'"

echo "spacebar configuration loaded.."
