#!/usr/bin/env sh
spacebar -m config position             top
spacebar -m config height               25
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15

spacebar -m config text_font            "FiraCode Nerd Font:Bold:12.0"
spacebar -m config icon_font            "FiraCode Nerd Font:Regular:12.0"

spacebar -m config background_color     0xff202020
spacebar -m config foreground_color     0xffa8a8a8
spacebar -m config space_icon_color     0xff458588
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xffa8a8a8
spacebar -m config clock_icon_color     0xffa8a8a8

spacebar -m config title                on

spacebar -m config spaces               on
spacebar -m config space_icon           unnamed
# spacebar -m config space_icon_strip        
spacebar -m config space_icon_strip     code personal web notes media zoom games

spacebar -m config clock                on
spacebar -m config clock_icon           
spacebar -m config clock_format         "%m/%d/%y %R"

spacebar -m config power                on
spacebar -m config power_icon_strip      
