# openssl-info.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-info.1ssl.gz
complete -c 'openssl-info.1ssl' -o help -d 'Print out a usage message'
complete -c 'openssl-info.1ssl' -o configdir -d 'Outputs the default directory for OpenSSL configuration files'
complete -c 'openssl-info.1ssl' -o enginesdir -d 'Outputs the default directory for OpenSSL engine modules'
complete -c 'openssl-info.1ssl' -o modulesdir -d 'Outputs the default directory for OpenSSL dynamically loadable modules other …'
complete -c 'openssl-info.1ssl' -o dsoext -d 'Outputs the \\s-1DSO\\s0 extension OpenSSL uses'
complete -c 'openssl-info.1ssl' -o dirnamesep -d 'Outputs the separator character between a directory specification and a filen…'
complete -c 'openssl-info.1ssl' -o listsep -d 'Outputs the OpenSSL list separator character'
complete -c 'openssl-info.1ssl' -o seeds -d 'Outputs the randomness seed sources'

