# systemd-pcrphase.service
# Autogenerated from man page /usr/share/man/man8/systemd-pcrphase.service.8.gz
complete -c 'systemd-pcrphase.service' -l bank -d 'Takes the PCR banks to extend the specified word into'
complete -c 'systemd-pcrphase.service' -l tpm2-device -d 'Controls which TPM2 device to use'
complete -c 'systemd-pcrphase.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-pcrphase.service' -l version -d 'Print a short version string and exit'
complete -c 'systemd-pcrphase.service' -l phase -d 'switch).  OPTIONS'

