#!/usr/bin/env sh

# label spaces
yabai -m space 1 --label main

# float system preferences. Most of these just disable Yabai form resizing them.
yabai -m rule --add app="^App Store$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="Archive Utility$" sticky=on layer=above manage=off
# yabai -m rule --add app="Fantastical" manage=off
# yabai -m rule --add app="^TeamViewer$" sticky=off layer=above manage=off
# yabai -m rule --add app="^Keka$" sticky=on layer=above manage=off
# yabai -m rule --add app="^Spotify$" manage=off
# yabai -m rule --add app="^Flux$" manage=off
# yabai -m rule --add app="^Time Out$" manage=off
# yabai -m rule --add app="^perl_client_app$" manage=off
# yabai -m rule --add app="^console$" manage=off
# yabai -m rule --add app="^Harvest$" manage=off
# yabai -m rule --add app="^CiscoSparkHelper$" manage=off
# yabai -m rule --add app="^Logi Options$" manage=off
# yabai -m rule --add app="^Cisco Webex Start$" manage=off
# yabai -m rule --add app="^Private Internet Access$" manage=off

# bar settings
# SPACEBAR_HEIGHT=$(spacebar -m config height)
# yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# global settings
yabai -m config mouse_follows_focus        off
yabai -m config focus_follows_mouse        off

yabai -m config window_placement           second_child
yabai -m config window_topmost             off
yabai -m config window_opacity             off
yabai -m config window_shadow              on

yabai -m config window_border              on
yabai -m config window_border_width        4
yabai -m config active_window_border_color 0xFFdfb899
yabai -m config normal_window_border_color 0xFF505050
yabai -m config insert_feedback_color      0xFFD75F5F

# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.90
yabai -m config split_ratio           0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout                bsp
yabai -m config top_padding           50
yabai -m config bottom_padding        5
yabai -m config left_padding          5
yabai -m config right_padding         5
yabai -m config window_gap            5

# killall spacebar &>/dev/null

echo "yabai configuration loaded.."
