#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bar settings
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# yabai -m config external_bar all:30:0

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          autoraise      \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        1.0            \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          6              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# mission-control desktop labels
yabai -m space 1 --label code
yabai -m space 2 --label personal
yabai -m space 3 --label web
yabai -m space 4 --label notes
yabai -m space 5 --label media
yabai -m space 6 --label zoom
# yabai -m space 7 --label gaming

# specific space settings
yabai -m config --space personal layout stack
yabai -m config --space zoom layout float
# yabai -m config --space gaming layout float

# float system preferences. Most of these just disable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^App Store$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="Archive Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^Python$" layer=above manage=off

# Todo application
yabai -m signal --add event=application_visible app='^Fantastical Helper$' \
  action="yabai -m window 25826 --ratio abs:0.8"

echo "yabai configuration loaded.."
