-- load_config
require('plugins.lsp')
-- require('plugins.nvim-tree')
require('plugins.nerdtree')
require('plugins.telescope')

require('plugins.latex')
require('plugins.goyo')

require('plugins.indentline')
require('plugins.colorizer')
require('plugins.floaterm')
require('plugins.fugitive')
require('plugins.git-messenger')
require('plugins.markdown')
require('plugins.neoformat')
require('plugins.nvim-autopairs')
require('plugins.quick-scope')
require('plugins.statusline')
-- require('plugins.galaxyline')
require('plugins.tagbar')
require('plugins.treesitter')
require('plugins.ultisnips')
require('plugins.undotree')
require('plugins.vimspector')
require('plugins.nvim-comment')
